version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: purple-note-frontend
    restart: unless-stopped
    networks:
      - purple-note-network
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  # 后端服务（使用已构建的镜像）
  backend:
    image: purplenote
    ports:
      - "8080:8080"
    container_name: purple-note-backend
    restart: unless-stopped
    networks:
      - purple-note-network
    # environment:
    #   - SPRING_PROFILES_ACTIVE=prod
      # 根据需要添加其他环境变量
      # - DB_HOST=database
      # - DB_PORT=3306

networks:
  purple-note-network:
    driver: bridge